language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
script: ./gradlew clean build
after_success:
  - bash <(curl -s https://codecov.io/bash) -t ad1cf46f-bc44-40a3-ba43-ec6e132750d8